version: "3"

services:
  app:
    container_name: demo-node16-ts
    build:
      context: .
      dockerfile: Dockerfile
    image: ts-node16-demo-api:latest
    volumes:
      - ./src:/app/src
    ports:
      - "5001:5000"
